project:
  type: website
  pre-render: preprocess_pip.py

website:
  title: "Sam Bailey | Data Science"
  favicon: favicon.png
  repo-url: https://github.com/sam-bailey/sam-bailey.github.io
  repo-branch: master
  site-url: https://sambailey.me
  navbar:
    title: Sam Bailey | Data Science
    background: light
    foreground: dark
    right:
      - index.qmd
      - publications.qmd
      - about.qmd
      - icon: github
        href: https://github.com/sam-bailey
      - icon: linkedin
        href: https://www.linkedin.com/in/sam-bailey-data-scientist
format:
  html:
    theme: 
      - simplex
      - custom.scss
    css: styles.css
    fontsize: 1.1em
    html-math-method: webtex
    smooth-scroll: true
    link-external-newwindow: true
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,300;0,600;1,300;1,600&family=JetBrains+Mono:ital,wght@0,200;0,600;1,200;1,600&family=Roboto+Mono:ital,wght@0,300;0,600;1,300;1,600&display=swap" rel="stylesheet">

execute:
  freeze: auto

mainfont: Bitter
monofont: JetBrains Mono
monofontoptions:
  - Scale=0.5