project:
  type: website
  pre-render: preprocess_pip.py

website:
  title: "Sam Bailey | Data Science"
  repo-url: https://github.com/sam-bailey/sam-bailey.github.io
  repo-branch: master
  navbar:
    title: Sam Bailey | Data Science
    background: info
    foreground: light
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/sam-bailey
      - icon: linkedin
        href: https://www.linkedin.com/in/sam-bailey-data-scientist
format:
  html:
    theme: journal
    css: styles.css

execute:
  freeze: auto
