project:
  type: website

website:
  title: "Sam's Data Stuff"
  navbar:
    background: light
    foreground: dark
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: journal
    css: styles.css

execute:
  freeze: auto
    